{% set name = "sphinx-simplepdf" %}
{% set version = "1.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/sphinx-simplepdf-{{ version }}.tar.gz
  sha256: bc8412c6b029886ae2e9241612dfc59c4cd35fa8cf2e7eb987c14126d422a939

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - sphinx
    - weasyprint
    - libsass
    - beautifulsoup4

test:
  imports:
    - sphinx_simplepdf
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://sphinx-simplepdf.readthedocs.io
  summary: An easy to use PDF Builder for Sphinx with a modern PDF-Theme.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - melund
